name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Wait for check step to finish
    # only run if tag is present on branch 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          preset: "conventionalcommits"
          skip-git-pull: true
          git-message: '🐳 chore(release): Update Changelog {version}'
          output-file: CHANGELOG.md
      #- name: Cache
      #  id: cache-dependencies
      #  uses: actions/cache@v3
      #  with:
      #    path: |
      #        **/node_modules
      #    key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      #- name: Installing Dependencies
      #  if: steps.cache-dependencies.outputs.cache-hit != 'true'
      #  run: npm install

      #- name: Running Build
      #  run: npm run build

      #- name: Running Test
      #  run: npm run test-unit

      #- name: Running Publish
      #  run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}