name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Commit changelog
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "📝 Update changelog"
          git push
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
              **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install

      - name: Running Build
        run: npm run build

      #- name: Running Test
      #  run: npm run test-unit

      - name: Running Publish
        run: npm publish
        env:
          # NPM_TOKEN is access token
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}